config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "contents#index"
  get 'home' => 'home#index'
  resources :contents, param: :uid
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/uid_module.rb
module UidModule
  extend ActiveSupport::Concern
  included do
    after_create :insert_uid
    def insert_uid
      self.attributes = {uid: SecureRandom.hex(4) + self.id.to_s + SecureRandom.hex(4)}
      self.save(validate: false)
    end

    def to_param
      uid
    end
  end
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :user
  include UidModule
  def soft_destroy
    update(deleted_at: Time.current)
  end

  def self.active
    where(deleted_at: nil)
  end

  def save_generated_output
    update(output_body: generate_output)
  end

  def generate_output
    Content.generate_a_sentence(input_words)
  end

  def self.generate_a_sentence(keyword)
    require 'net/http'
    uri = URI.parse("https://api.openai.com/v1/completions")
    req = Net::HTTP::Post.new(uri)
    body = {"model": "text-davinci-003", "temperature": 0.2, "max_tokens": 20}
    keywords_txt = keyword
    body["prompt"] = "create a sentence in English with: #{keywords_txt}"
    req.body = body.to_json
    headers = { "Authorization" => "Bearer #{ENV['OPENAI_KEY']}", "Content-Type" => "application/json" };
    headers.each{|name, value| req[name] = value}
    http = Net::HTTP.start(uri.hostname, uri.port, use_ssl: true)
    response_raw = http.request(req)
    response = JSON.parse(response_raw.body)
    response["choices"][0]["text"].strip!
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :contents
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        #  :confirmable, :lockable, :timeoutable, :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
    before_action :set_content, only: %i(show edit update destroy)
    before_action :authenticate_user!, only: %i(new create edit update destroy)
    def index
        @contents = Content.active
    end

    def show
    end

    def new
      @content = current_user.contents.new
    end

    def create
      @content = current_user.contents.new(content_params)
      if @content.save
        @content.save_generated_output
        redirect_to contents_path
      else
        render :edit
      end
    end

    def edit

    end

    def update
      if @content.update(content_params)
        @content.save_generated_output
        redirect_to @content
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @content.soft_destroy
      redirect_to contents_path, notice: '削除しました'
    end

    private
    def set_content
        @content = Content.find_by(uid: params[:uid])
    end

    def content_params
        params.require(:content).permit(:input_words)
    end

    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/contents/_form.html.slim
= form_with model: @content, html: {class:'space-y-6'} do |f|
  - if @content.errors.any?
    #error_explanation.p-4.bg-blue-100
      ul
        - @content.errors.full_messages.each do |message|
          li = message
  div
    .sm:mx-auto.sm:w-full.sm:max-w-
      svg.block.mx-auto.w-12.h-12[xmlns="http://www.w3.org/2000/svg" fill="none" viewbox="0 0 24 24" stroke-width="1.5" stroke="currentColor"]
        path[stroke-linecap="round" stroke-linejoin="round" d="M7.5 8.25h9m-9 3H12m-9.75 1.51c0 1.6 1.123 2.994 2.707 3.227 1.129.166 2.27.293 3.423.379.35.026.67.21.865.501L12 21l2.755-4.133a1.14 1.14 0 01.865-.501 48.172 48.172 0 003.423-.379c1.584-.233 2.707-1.626 2.707-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z"]
    h2.mt-10.text-center.text-3xl.font-bold.tracking-tight.text-gray-700
      | 英文ジェネレーター
    p.mt-2.text-center.text-sm.text-gray-600
      |  入力した英単語を含んだ英文をAIが生成します。
    label.block.text-sm.font-medium.text-gray-700.mt-5
      | 英単語
    .mt-1
      = f.text_field :input_words, class: 'block w-full appearance-none rounded-md border border-gray-300 px-3 py-2 placeholder-gray-400 shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm'
  div
    = f.submit '生成する', class: 'flex w-full justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 mt-5'

app/views/contents/edit.html.slim
.flex.justify-between.items-center.mb-8
  div
    = link_to @content, class: 'flex' do
      svg.block.w-6.h-6[xmlns="http://www.w3.org/2000/svg" fill="none" viewbox="0 0 24 24" stroke-width="1.5" stroke="currentColor"]
        path[stroke-linecap="round" stroke-linejoin="round" d="M15.75 19.5L8.25 12l7.5-7.5"]
      div 戻る
  div
    = @content.input_words
    | の編集
= render 'form'

app/views/contents/index.html.slim
.mx-auto.w-full
  .relative.sm:py-16.lg:py-0
    .hidden.sm:block.lg:absolute.lg:inset-y-0.lg:right-0.lg:w-screen[aria-hidden="true"]
      .absolute.inset-y-0.right-1/2.w-full.rounded-r-3xl.bg-gray-50.lg:right-72
      svg.absolute.top-8.left-1/2.-ml-3.lg:-right-8.lg:left-auto.lg:top-12[width="404" height="392" fill="none" viewbox="0 0 404 392"]
        defs
          pattern#02f20b47-fd69-4224-a62a-4c9de5c763f7[x="0" y="0" width="20" height="20" patternunits="userSpaceOnUse"]
            rect.text-gray-200[x="0" y="0" width="4" height="4" fill="currentColor"]
        rect[width="404" height="392" fill="url(#02f20b47-fd69-4224-a62a-4c9de5c763f7)"]
    .relative.mx-auto.max-w-md.px-1.sm:max-w-3xl.lg:max-w-none.lg:px-0.lg:py-20
      .text-right.mb-4.pr-1
        button.inline-flex.items-center.rounded-md.border.border-transparent.bg-indigo-900.px-4.py-2.text-sm.font-medium.text-white.shadow-sm.hover:bg-indigo-700.focus:outline-none.focus:ring-2.focus:ring-indigo-500.focus:ring-offset-2[type="button"]
          svg.-ml-1.mr-2.h-5.w-5[xmlns="http://www.w3.org/2000/svg" viewbox="0 0 20 20" fill="currentColor" aria-hidden="true"]
            path[d="M10.75 4.75a.75.75 0 00-1.5 0v4.5h-4.5a.75.75 0 000 1.5h4.5v4.5a.75.75 0 001.5 0v-4.5h4.5a.75.75 0 000-1.5h-4.5v-4.5z"]
          span
            = link_to 'AI 英文生成', new_content_path, class: ''
      .relative.overflow-hidden.rounded-2xl.pt-12.pb-10.shadow-xl
        .absolute.inset-0.bg-indigo-500.mix-blend-multiply.z-0
        .absolute.inset-0.bg-gradient-to-t.from-indigo-600.via-indigo-600.opacity-90
        .relative.px-8
          div
            img.h-12[src="#{image_url('yourworks.png')}" alt="Workcation"]
          blockquote.mt-8
            .relative.text-lg.font-medium.text-white.md:flex-grow
              svg.absolute.top-0.left-0.h-8.w-8.-translate-x-3.-translate-y-2.transform.text-indigo-400[fill="currentColor" viewbox="0 0 32 32" aria-hidden="true"]
                path[d="M9.352 4C4.456 7.456 1 13.12 1 19.36c0 5.088 3.072 8.064 6.624 8.064 3.36 0 5.856-2.688 5.856-5.856 0-3.168-2.208-5.472-5.088-5.472-.576 0-1.344.096-1.536.192.48-3.264 3.552-7.104 6.624-9.024L9.352 4zm16.512 0c-4.8 3.456-8.256 9.12-8.256 15.36 0 5.088 3.072 8.064 6.624 8.064 3.264 0 5.856-2.688 5.856-5.856 0-3.168-2.304-5.472-5.184-5.472-.576 0-1.248.096-1.44.192.48-3.264 3.456-7.104 6.528-9.024L25.864 4z"]
                  - @contents.each do |content|
                    li= link_to content.input_words, content
      - if user_signed_in?
        .text-right.mt-3.pr-1
          button.inline-flex.items-center.rounded-md.border.border-transparent.bg-indigo-900.px-4.py-2.text-sm.font-medium.text-white.shadow-sm.hover:bg-indigo-700.focus:outline-none.focus:ring-2.focus:ring-indigo-500.focus:ring-offset-2[type="button"]
            span
              = link_to 'ログアウト', destroy_user_session_path, method: :delete

app/views/contents/new.html.slim
= link_to contents_path, class: 'flex' do
  svg.block.w-6.h-6[xmlns="http://www.w3.org/2000/svg" fill="none" viewbox="0 0 24 24" stroke-width="1.5" stroke="currentColor"]
    path[stroke-linecap="round" stroke-linejoin="round" d="M15.75 19.5L8.25 12l7.5-7.5"]
  div 一覧
.bg-white.pt-4.pb-16.px-4.mt-4.shadow.sm:rounded-lg.sm:px-10
  = render 'form'

app/views/contents/show.html.slim
.flex.items-center.mb-8
  div
    = link_to contents_path, class: 'flex' do
      svg.block.w-6.h-6[xmlns="http://www.w3.org/2000/svg" fill="none" viewbox="0 0 24 24" stroke-width="1.5" stroke="currentColor"]
        path[stroke-linecap="round" stroke-linejoin="round" d="M15.75 19.5L8.25 12l7.5-7.5"]
      div 一覧
- if @content.output_body.present?
  p.bg-gray-200.px-4.py-3
    = @content.output_body
- else 
  p.bg-yellow-200.px-4.py-3 
    | 生成エラー
.flex.justify-between.items-center.mb-8.mt-5
  p
    | 登録された単語は #{@content.input_words}
  div
    = link_to edit_content_path, class: 'inline-flex items-center rounded border border-gray-300 bg-white px-2.5 py-1.5 text-xs font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2' do
      div 編集


/ div.text-right.mt-3
/   = link_to edit_content_path, class: 'flex inline-flex items-center rounded-md border border-transparent bg-indigo-600 px-3 py-2 text-sm font-medium leading-4 text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"' do
/     div 編集
/ h2.mt-3
/   | 登録された単語は #{@content.input_words}

app/views/home/index.html.slim
p hello

app/views/layouts/application.html.slim
doctype html
html
  head
    title English Sentence Generator
    meta name="viewport" content="width=device-width,initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"

    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  body
    .flex.min-h-full.flex-col.justify-center.py-10.px-4.sm:px-6.lg:px-8
      .mt-2.sm:mx-auto.sm:w-full.sm:max-w-xl
        main class=""
        - if user_signed_in?
          .flex.justify-center.p-2.my-5
            svg.mr-1.h-5.w-5.text-indigo-500[xmlns="http://www.w3.org/2000/svg" viewbox="0 0 20 20" fill="currentColor" aria-hidden="true"]
              path[fill-rule="evenodd" d="M16.704 4.153a.75.75 0 01.143 1.052l-8 10.5a.75.75 0 01-1.127.075l-4.5-4.5a.75.75 0 011.06-1.06l3.894 3.893 7.48-9.817a.75.75 0 011.05-.143z" clip-rule="evenodd"]
            div Hello #{current_user.email.sub!(/@.*/m, "")}
        p class="notice text-center"
          = notice
        p class="alert text-center"
          = alert
        = yield